In [ ]:
wat = 'watson'
print(wat)

#  Hashing of Password

FIRST import os

In [1]:
import os

THEN import hashlib from library

In [2]:
import hashlib

### _Generation_ _example_

In [3]:
# generate Salt at 32byte
salt = os.urandom(32)   #Unique random string known only to the site for each password!

# hashing password and key derivation funct using hmac, (utf-8, byte conversion)
key = hashlib.pbkdf2_hmac('sha256', 'mypassword'.encode('utf-8'), salt, 100000)

#store "salt and key" in a variable
storage = salt + key

# Getting the values back
salt_from_storage = storage[:32]
key_from_storage = storage[32:]

### Verification

In [4]:
import hashlib

In [5]:
salt = b'' # Get the salt you stored for this user
key = b'' # Get this users key calculated

password_to_check = 'password246' # Provided password by this user

_Using the exact same setup used in generating the key_

In [6]:
new_key = hashlib.pbkdf2_hmac('sha256', password_to_check.encode('utf-8'), salt, 100000)   #stored in new Variable

# iterate
if new_key == key:
    print('Password is a GO')
else:
    print('Screwed')

Screwed


### JUST HATCHED and verification failed!

# Round2 _(hashing)_:

In [7]:
# Creation of Username and password for a specific client

import hashlib
import os

users = {}     # A simple demo storage

# Add a user
username = 'brentwood'
password = 'oluwa1234'

salt = os.urandom(32)    # A new salt for this user
key = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, 100000)
users[username] = {   # store the salt and key!
    'salt': salt,
    'key': key
}

In [8]:
print(key)
print(salt)

b'W\x88\xa0\x9c(\x0cll,\xce\xc2O\x91\x16*\x86=\xf3\x97)\xa7y\x7fq\xdb*3Qh\x80\xd1\xa4'
b'J\x94VF\x92\xed#[\xcec\x9ag\xd8\xd8\x97\x13\xecJ\x0fz\xc9\xe4\x17\x84\x969bA\x1b\xb3\xf0\xfc'


### Verification attempt 1 (Wrong password)

In [9]:
username = 'brentwood'
password = 'oluwaburna'

salt = users[username]['salt'] # Get the salt
key = users[username]['key']   # Get correct key
new_key = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, 100000)

if new_key == key:
    print('Password is a GO')
else:
    print('Screwed')

Screwed


In [10]:
print(key)
print(salt)

b'W\x88\xa0\x9c(\x0cll,\xce\xc2O\x91\x16*\x86=\xf3\x97)\xa7y\x7fq\xdb*3Qh\x80\xd1\xa4'
b'J\x94VF\x92\xed#[\xcec\x9ag\xd8\xd8\x97\x13\xecJ\x0fz\xc9\xe4\x17\x84\x969bA\x1b\xb3\xf0\xfc'


### Verification  attempt 2 (Correct password)

In [11]:
username = 'brentwood'
password = 'oluwa1234'

salt = users[username]['salt'] # Get the salt
key = users[username]['key']   # Get correct key
new_key = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, 100000)

if new_key == key:
    print('Password is a GO')
else:
    print('Screwed')

Password is a GO


In [12]:
print(key)
print(salt)

b'W\x88\xa0\x9c(\x0cll,\xce\xc2O\x91\x16*\x86=\xf3\x97)\xa7y\x7fq\xdb*3Qh\x80\xd1\xa4'
b'J\x94VF\x92\xed#[\xcec\x9ag\xd8\xd8\x97\x13\xecJ\x0fz\xc9\xe4\x17\x84\x969bA\x1b\xb3\xf0\xfc'


### Adding a different user

In [13]:
username = 'derick'
password = 'my$ecur3p@$$w0rd'
key = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, 100000)
users[username] = {   # store the salt and key in a "Demo Storage"
    'salt': salt,
    'key': key
}

In [14]:
print(key)
print(salt)

b'\x7f\xc3\x84\xa3\xf3\xa3\xbd\x93\x80\x98\x8c\xee\x15\xe8\xdfx\x92v;M\x1a\xe8\x89h\x86\xd8\xae\x1a\xf7\x12\xc0\xd8'
b'J\x94VF\x92\xed#[\xcec\x9ag\xd8\xd8\x97\x13\xecJ\x0fz\xc9\xe4\x17\x84\x969bA\x1b\xb3\xf0\xfc'


### Checking the other users password

In [15]:
username = 'derick'
password = 'myecur3p@$$w0rd'

salt = users[username]['salt'] # Get the salt
key = users[username]['key']   # Get correct key
new_key = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, 100000)

if new_key == key:
    print('Welcome home')
elif username == username:
    print('Talk to Admin')
else:
    print('Screwed')


Talk to Admin


# Today's Work!

## _Getting today's date and time_

In [2]:
import datetime
while True:
    print('Do I want today\'s date and time ? (y/n): ')
    check = input()
    if check == 'n':          #Note to self, more functions on check????
            break
    else:
        print('today\'s date and time:')
        print(datetime.datetime.today())
        print()
        
        break
          

Do I want today's date and time ? (y/n): 


 y


today's date and time:
2022-10-13 10:33:01.477354



In [ ]:
import datetime
print(datetime.datetime.today())
    

In [ ]:
w = 'bag'
a = 'bat'
print('a is not the same as b, (y/n):')
check = input()  #To open a command / checking box
if check == n:
        break
else:
    print('unique')

In [ ]:
import datetime
while True:
    print('Wanna know the Date? (y/n): ')
    check = input()
    if check == 'n':
            break
    else:
        print('today\'s date and time:')
        print(datetime.datetime.today())

Wanna know the Date? (y/n): 
y
today's date and time:
2022-03-21 15:48:33.833377
Wanna know the Date? (y/n): 


In [4]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [1]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

2022-05-16 22:27:14.268840: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/5
1875/1875 [==============================] - 6s 2ms/step - loss: 0.2973 - accuracy: 0.9127
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1434 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1087 - accuracy: 0.9672: 0s - l
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0874 - accuracy: 0.9734
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0702 - accuracy: 0.9802


[0.07018651813268661, 0.9801999926567078]

In [2]:
rank1_tensor = tf.Variable(['Test', 'Ok', 'Tim'],['job', 'hub', 'tub'], tf.string)
rank2_tensor = tf.Variable(['Test', 'Ok', 'Tim'], tf.string)

In [3]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
fashion_mnist = tf.keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [5]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.6.3


#### Load and prepare the MNIST dataset. Convert the sample data from integers to floating-point numbers:

In [26]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# Build a machine learning model
#### Build a tf.keras.Sequential model by stacking layers.

Importance and significant role of keras to Machine Learning??

In [27]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [28]:
predictions = model(x_train[:1]).numpy()
predictions            # converts each model to logits

array([[ 0.18852004,  0.45759806, -1.3295637 , -0.13844027, -0.0849997 ,
        -0.02065983,  0.3253296 , -0.20067705,  0.10981667, -0.71511286]],
      dtype=float32)

#### The tf.nn.softmax function converts these logits to probabilities for each class:
An array is faster python list and numpy can sort through arrays

In [31]:
tf.nn.softmax(predictions).numpy()    # makes it more intepretable 

array([[0.12539865, 0.1641164 , 0.02747878, 0.09042652, 0.09539042,
        0.10172957, 0.14378333, 0.08497021, 0.11590774, 0.05079841]],
      dtype=float32)

Define a loss function for training using losses.SparseCategoricalCrossentropy, 
which takes a vector of logits and a True index and returns a scalar loss for each example.

In [32]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [33]:
loss_fn(y_train[:1], predictions).numpy()

2.285437

##### This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.
_This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3._

##### Before you start training, configure and compile the model using Keras Model.compile. Set the optimizer class to adam, set the loss to the loss_fn function you defined earlier, and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.

In [38]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])    # Configuring the ML

### Train and evaluate your model
Use the Model.fit method to adjust your model parameters and minimize the loss:

In [40]:
model.fit(x_train, y_train, epochs=5) # Adjust the above parameters

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0651 - accuracy: 0.9799
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0578 - accuracy: 0.9822
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0521 - accuracy: 0.9832
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0482 - accuracy: 0.9843
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0433 - accuracy: 0.9857


### Checkn Model's performance
Use the "Model.evaluate" method checks the models performance, usually on a "Validation-set" or "Test-set".

In [41]:
model.evaluate(x_test,  y_test, verbose=2)    #??

313/313 - 0s - loss: 0.0702 - accuracy: 0.9804


[0.07024403661489487, 0.980400025844574]

The image classifier is now trained to ~98% accuracy on this dataset||

In [42]:
print('')

#### Attempting to return back to probability
If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [43]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [63]:
probability_model(x_test[:-1])

<tf.Tensor: shape=(9999, 10), dtype=float32, numpy=
array([[1.85731031e-11, 2.60233377e-13, 6.86530566e-09, ...,
        9.99998212e-01, 5.60720970e-10, 1.22928672e-08],
       [1.38505852e-12, 5.19823402e-08, 1.00000000e+00, ...,
        1.37424349e-19, 1.00260564e-10, 1.46508615e-19],
       [4.53051152e-09, 9.99681473e-01, 8.01318129e-06, ...,
        2.92996119e-04, 1.23933642e-05, 8.31174702e-08],
       ...,
       [2.61775107e-12, 7.31274552e-09, 1.53886003e-06, ...,
        8.21895468e-11, 2.32208267e-10, 2.28065596e-06],
       [3.17230949e-14, 2.38091534e-12, 5.28964325e-15, ...,
        1.91844174e-06, 4.83425744e-08, 4.91593200e-05],
       [1.91450696e-12, 9.54869647e-13, 1.38215253e-14, ...,
        5.23149883e-12, 8.84852398e-06, 5.32821599e-11]], dtype=float32)>

#### Congratulations! You have trained a machine learning model using a prebuilt dataset using the Keras API.

In [50]:
import numpy as np

print(np.__version__)

1.19.5


## Keras    
Keras is an open-source software library that provides a Python interface for artificial neural networks
### Sequential model        ⇈

SETUP

In [49]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

### Creating a sequenciial model

You can create a Sequential model by passing a list of layers to the Sequential constructor:

In [53]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu"),
        layers.Dense(3, activation="relu"),
        layers.Dense(4),
    ]
)          # Its layers are accessible via the layers attribute:

In [55]:
model.layers

##### You can also create a Sequential model incrementally via the add() method: