In [44]:
set_to_true = True
set_to_false = False # Using Bool to create a bolean variable

In [45]:
set_to_true

True

In [46]:
set_to_false

False

In [47]:
bool_one = 5 != 7
bool_two = 1 + 1 != 2
bool_three = 3 * 3 == 9

print(bool_one)   
print(bool_two)    
print(bool_three)  # creating a bolean variable
print(type(bool_three))

True
False
True
<class 'bool'>


- Boolean variables are the building blocks of CONDITIONAL STATEMENTS!
- Relational operators
- Boolean operators

In [48]:
if bool_one == bool_three:
    print('watever')        #Both are True

watever


In [49]:
(2 + 2 + 2 >= 6) and (-1 * -1 < 0)

False

In [50]:
(4 * 2 <= 8) and (7 - 1 == 6)

True

In [51]:
(2 - 1 > 3) or (-5 * 2 == -10)

True

In [52]:
(9 + 5 <= 15) or (7 != 4 + 3)

True

In [53]:
not 1+1==2  #should be True

False

In [54]:
not 7 < 0 #should be False

True

In [55]:
not (8 * 2) != 20 - 4

True

In [69]:
credits = 112
gpa = 2.0
if not credits >= 120:
    print("You do not have enough credits to graduate.")

You do not have enough credits to graduate.


In [77]:
if not credits >= 120 and not gpa >= 4.0:
    print("You do not meet either requirement to graduate!")

You do not meet either requirement to graduate!


In [73]:
if not gpa >= 2.0:
    print("Your GPA is not high enough to graduate.")

In [88]:
weekday = ('sat')
if weekday == 'mon':
    print('workday')
elif weekday == 'tues':
    print('new week')
else:
    print('weekend')

weekend


In [90]:
Altheda = 'Girl'
Fremont = 'Boy'
Audrey = 'girl'

In [111]:
if Audrey == 'girl' and Fremont == 'Boy' and Altheda == 'Girl':
    print('yes')
else:
    print("NO")

yes


In [109]:
donation = 700
print("Thank you for the donation!")
if donation >= 1000:
  print("You've achieved platinum status")
elif donation >= 500:
  print("You've achieved gold donor status")
elif donation >= 100:
  print("You've achieved silver donor status")
else:
  print("You've achieved bronze donor status")

Thank you for the donation!
You've achieved gold donor status


In [108]:
password = 'kingkong'


if password == 'kingkon':
    print("Welcome")
else:
    print('invalid input')

invalid input


In [112]:
import tensorflow as tf

In [113]:
import numpy as np

In [135]:
x = tf.ones([3,2,3])

In [136]:
x

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [137]:
y = tf.zeros([3,3,3])

In [138]:
y

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>